### ISSUE TITLE
Problem in changing picture and social handle

### ISSUE THREAD

**Issue by lavangnadubey** [tanaypratap/tanay-demo-blog#3]
hey, I have uploaded the pic , it is showing in the codesandbox but it is not showing in the blog after commiting . And also how can i change the twiiter ( social ) to some other social media ,i tried changing but then errors afre coming .

**Comment by tanaypratap** [comment]
Please give your codesandbox link.
Also, this Twitter thing is because it's hard-coded in Bio component.
Check the Bio component and make the necessary changes.

**Comment by lavangnadubey** [comment]
sir , i have made changes directly in the git master directory ..now everything is working fine..thank you for your help : )
